Python 3.14.3 (tags/v3.14.3:323c59a, Feb  3 2026, 16:04:56) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> print("Welcome to FizzBuzz!")
... 
... 
... max_number = int(input("Enter a maximum number: "))
... 
... 
... for number in range(1, max_number + 1):
... 
... 
...     if number % 3 == 0 and number % 5 == 0:
...         print(f"{number} - FizzBuzz")
... 
...     
...     elif number % 3 == 0:
...         print(f"{number} - Fizz")
... 
...     
...     elif number % 5 == 0:
...         print(f"{number} - Buzz")
... 
...     
...     else:
...         print(number)
... 
